# Generated by Django 2.1.7 on 2019-03-27 21:42

import colorfield.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('image', models.ImageField(upload_to=core.models.custom_profile_upload_to, verbose_name='Imagen')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profesión')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('biography', models.TextField(verbose_name='Biografía')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('isPublished', models.BooleanField(default=False, unique=True, verbose_name='Publicar')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Habilidad')),
                ('image', models.ImageField(upload_to=core.models.custom_skill_upload_to, verbose_name='Logo')),
                ('color', colorfield.fields.ColorField(default='#2c98f0', max_length=18, verbose_name='Color del logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='get_profiles', to='core.Skill', verbose_name='Habilidades'),
        ),
    ]
